### ISSUE TITLE
Swap out RegExp for RE2

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#136]
This is for performace improvements.

**Comment by silentrob** [comment]
I should also point out there are others to consider too
http://lh3lh3.users.sourceforge.net/reb.shtml

https://www.npmjs.com/package/oniguruma

**Comment by ianp** [comment]
If you're OK with the code style & so on, I'll submit a PR for these changes.

**Comment by benhjames** [comment]
We're back to not using RE2! We managed to offset a lot of the performance hit of using regexes by changing the way we do normalisation, going from several thousand to ~50 per normalisation.

There seems to be too little (if any?) performance gain now to justify the complexity of RE2, which is currently the only dependency that involves setting up build tools on user's systems (to build the C source).
