### ISSUE TITLE
integration superscript w/ application

### ISSUE THREAD

**Issue by ArkeologeN** [superscriptjs/superscript#141]
I'm not using superscript as a standalone but instead using it's bot logic and data population w/ my existing database model.

My application has `User` model so superscript do. I want to extend the `superscript`'s mongoose model fro `Users` to add few of my model related fields as well.

 Is there any abstraction available?

**Comment by ArkeologeN** [comment]
Ping? Its a blocker now it should be reconsidered. There must be a way to explicitly provide the schema for User.

**Comment by silentrob** [comment]
Im not sure exactly what you are describing, but I think it falls well outside the primary use case of superscript and might be better considered for a fork.

**Comment by ArkeologeN** [comment]
@silentrob You have defined `User` model within your `SS` which makes it impossible for us to write exactly same mongoose model `User` because it raises `Cannot overwrite 'users' model once compiled.`.

Now, we cannot rename our model and need to use `superscript`'s `User` model to extend add new fields i.e emailAddress etc..

**Comment by planetceres** [comment]
I would also be interested to use it with an existing database model as @ArkeologeN suggests. Seems to limit the potential applications by not allowing to write to the same user model, but maybe that's the intention.

**Comment by ArkeologeN** [comment]
@planetceres I think they can rename it or explicitly allow to modify schema object. It could be something like this:

```javascript
var superscript = require('superscript');
super.setUserSchema(new Schema({ password: String }));
```

where `setUserSchema` will take an instance of `mongoose.Schema` and inside, it would merge our schema fields with it's own.

**Comment by planetceres** [comment]
I'm not sure I completely follow. How are you getting the user model instance from superscript in that example?

**Comment by ArkeologeN** [comment]
Errm I guess it was some nested object on `superscript` but ofcourse you cannot recompile a compiled model. The above reply was a specification I suggested to make it work.

**Comment by benhjames** [comment]
In v1.0.0 we're renaming `User` to `ss_user` to avoid name collisions.

**Comment by ArkeologeN** [comment]
:+1:
