### ISSUE TITLE
Option to match concepts against own list rather than Wordnet

### ISSUE THREAD

**Issue by mariusursache** [superscriptjs/superscript#154]
@silentrob based on our Slack chat:

How can we disable concept matching with Wordnet, and use instead own concepts defined in a list such as [this one](https://github.com/silentrob/superscript/blob/master/test/fixtures/concepts/concepts.top).

The reason is that Wordnet matching is very weird. For example, using

`i ~like ~sports`

Tries to match `~like` against
- cotton
- prefer
- care for
- love
- please

and `~sports` against
- jocosity
- waggery
- drollery
- pun
- freak
- professional boxing
- professional wrestling
- sumo
- professional golf
- professional football
- professional baseball
- professional basketball
- professional tennis
- funambulism
- rock climbing
- contact sport
- outdoor sport
- gymnastics
- track and field
- skiing
- water sport
- rowing
- archery
- sledding
- skating
- racing
- riding
- cycling
- blood sport
- athletic game
- judo 
- spectator sport
- team sport

**Comment by planetceres** [comment]
Also, shouldn't `i ~like you` match the input `i like you'? 

When I use `i ~like you` as an input, it only matches the inputs:

- I cotton you
- I prefer you
- I care for you
- I love you
- I please you

but does NOT match:
- I like you

**Comment by silentrob** [comment]
I agree, this is an issue. I think it also extends into sfacts where in some cases we are referring to the concept as a synonym and other times it is a hypernym.

**Comment by benhjames** [comment]
I think this should work in v1:

* The word itself is added to the list of words it accepts, so `I ~like you` will now match `I like you` as well as the others.
* You can import data as an option on starting SuperScript, so you can just pass it a concept table like the one linked above and it'll populate the fact system.
* The fact system is preferred over using WordNet, so it'll expand concepts from your custom ones first.
