### ISSUE TITLE
Change the welcome message to a question

### ISSUE THREAD

**Issue by matteoraggi** [superscriptjs/superscript#155]
Do you think that it is ok to change the first message question of superscript in a welcome/question message?
For Example:
instead of this default message: "Welcome to the real-time editor."
I would like to write: "?:WH Good morning! Which fruits would you like to eat for breakfast?"

**Comment by mariusursache** [comment]
@matteoraggi, the Welcome message appears only in the editor, it's not coded in SS.

The way we do opening gambits is like this:

```
> pre

  + start
  - ^topicRedirect(newtopic,__open__)

< pre

> topic:system:keep newtopic

  + __open__
  - Oups, I just woke up. Good morning! Etc.

< topic
```

Does this help?

**Comment by benhjames** [comment]
I'd probably just either leave opening welcome messages to your application on a user connect, or do as suggested above.
