### ISSUE TITLE
Tests execution issues

### ISSUE THREAD

**Issue by karovski** [superscriptjs/superscript#158]
With the latest update (https://github.com/silentrob/superscript/commit/1c6ea3e204db24151b19cd9bb64fae8c41e4a1ef) the tests for redirects are the only ones running (`describe.only`).

Removing the `only` in order to run everything yields the following error:

```
1) Super Script Continue System aka Conversation "before all" hook:
     Uncaught Error: Trying to open unclosed connection.
```

Adding back `only` to `script.js` as it was previously results in all tests passing.

**Comment by karovski** [comment]
An additional note: the cached `script.json` from previous tests executions resulted in one failing test from `script.js`. I didn't note the test name but if needed I can try to reproduce it.

**Comment by silentrob** [comment]
Okay Im going to say this is related to gh-164. The cached script.json should not be in the repo. I find Im blowing that out all the time. Sorry for the flaky tests...

**Comment by benhjames** [comment]
Just did some housekeeping: all pending tests are now actual failing tests. Also have double-checked that cache files are in the gitignore.
