### ISSUE TITLE
Resetting a conversation chain based on last reply

### ISSUE THREAD

**Issue by DBozhinovski** [superscriptjs/superscript#161]
Consider the following scenario:

User initiates conversation, and there is an exchange of a couple of input / reply cycles. However, during the exchange, before completing a topic, the user loses their connection, or the session breaks for whatever reason.

Example: 

(copied from the bug tracker in our repo for eterni.me)

Test 1 (session interruption):

Send to bot lastreply step 1
Bot replies Test OK. LastReply is step 1
Send to bot lastreply step 2
Bot replies Test OK. LastReply exists
Send to bot lastreply step 1
Bot replies Test OK. LastReply is step 1
Break session (restart session?)
Send to bot lastreply step 2
Bot replies Test OK. LastReply does not exist
Test 2 (session timeout)

Replace step 7 with session timeout

In order to avoid awkward replies and getting stuck into a meaningless conversation, we thought about maybe deleting the input / reply chain for that topic from the users collection. Is this a good idea? Since it can potentially break things that depend on the conversation history?

Additionally, is this something suitable for the core of SuperScript? It might be useful have some sort of a criteria about what a meaningful conversation is, so that SuperScript can produce more "natural" results, even when a connection / session breaks.

**Comment by benhjames** [comment]
I think there's a couple of things that could help you here.

You could save "user currently completing form", "step 1 complete", "step 2 complete" as user facts, so when the user returns, the `pre` topic hook will redirect to the form-filling in topic, and it will pick up where it left off. I think there's some interesting work around these kinds of workflows that we could bake in to SS core.

Also, v1 exposed the conversation timeout to be configurable, so you could try bumping this up to something a lot higher, but just as a human forgets conversations, it's more natural to have it somewhere nearer the current limit of 5 minutes.
