### ISSUE TITLE
Failing and unused tests

### ISSUE THREAD

**Issue by karovski** [superscriptjs/superscript#164]
Currently the tests in `test/script.js` are the only ones that are executed. To my knowledge the tests in the other files are usually executed when a code change is done that can be related to a possibly affected functionality.

Not sure which tests are outdated or non-applicable at this point, so I ran every one separately to see the results.

(note: trying to run everything by removing the `.only` in `script.js` outright fails due to an unclosed connection error)

The following test are currently failing:

```
continue.js: 5 tests:
      1) should continue Sorted - B
      2) GH-84 - compound reply convo.
      3) Threaded Conversation
      4) Should not match
      5) Should be even more awesome

qtype.js: 5 tests:
      1) should not match
      2) should reply to QType string YN QType
      3) should reply to QType string B
      4) should reply to QType string C
      5) should match fine grained results

reason.js: 80 tests: (too many to list)

topicflags.js: 6 tests:
      1) should fetch a list of topics
      2) Go to hidden topic indirectly
      3) topic flow 1
      4) topic flow 2
      5) should keep topic for reuse
      6) should not repeat itself

topicsystem.js: 3 tests:
      1) Should try string agaist gambit
      2) update gambit test
      3) Should try string agaist topic
```

**Comment by silentrob** [comment]
You are right and clearly my approch does not scale very nicly or properly communicate the right intent. Ideally I would like to pair down the suite and have them all run. Or possible replace all the tests for more of a unit style test suite.

**Comment by silentrob** [comment]
Some of the reason tests add extra dependancies and they do (or did) work perhaps spinning those into a sepeerate project would be more appropiate.

**Comment by benhjames** [comment]
The test suite runs pretty nicely at the moment. We've also started splitting out tests into separate projects (e.g. `ss-message`) for a nice unit test-y feel.

I think for any additional splitting of unit tests we should create new issues to track them.
