### ISSUE TITLE
topicRedirect skipping reply

### ISSUE THREAD

**Issue by Lewwwk** [superscriptjs/superscript#171]
When trying to enter this topic

```
> topic:keep setup
  + setup
  - who are you?

  + *~2
  % who are you
  - ^save(name,<cap>) Nice to meet you <cap>! {topic=random}
< topic
```

it functions as expected if the input is 'setup'.  However, when entering it through a topic redirect, it jumps right through to to the second trigger. (redirect is triggered with 'redirect setup' input and the following ss:

```
+ redirect setup
- {keep} ^topicRedirect(setup,setup)
```

Update: redirect will actually pass through 'redirect setup' as the input into the second trigger in the topic. So, and input of 'redirect setup' in topic=random will lead to an output of 'Nice to see you redirect setup!'

**Comment by benhjames** [comment]
Should be fixed in v1.0.0, thanks for all the reports! :+1:
