### ISSUE TITLE
Filters in triggers work if included WITHOUT curly braces

### ISSUE THREAD

**Issue by Lewwwk** [superscriptjs/superscript#193]
The following pre filter works: 

```> pre
- ^hasName(false) *
  - {keep} Hi there! Welcome to SuperScript. 
    < pre ```

However this does not: 

```> pre
- {^hasName(false)} *
  - {keep} Hi there! Welcome to SuperScript. 
    < pre ```

**Comment by Lewwwk** [comment]
Noncritical - just helpful to know so logging here so it's searchable if someone is having problems.

**Comment by silentrob** [comment]
I suspect that is just for the gambit side.. The reply side should only work inside the curly brace.

**Comment by Lewwwk** [comment]
Correct

**Comment by benhjames** [comment]
In v1.0.0, gambits and replies will now use the same filter syntax *with* the curly braces.

```
+ {^aGambitFilter()} hey
- {^aReplyFilter()} sup
```
