### ISSUE TITLE
Another reply exhaustion scheme.

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#201]
Replies are exhausted in order unless there is a keep flag. I'm proposing a method to bring back all the replies only after they have all been exhausted. This is like turning the card deck discard pile back over when the cards are all gone.

I'm not sure how this would be implemented as it applies to the entire reply set or gambit.  Perhaps like this..

```
+ {reload replies} test input
- reply one
- reply two
- reply three
```

**Comment by mariusursache** [comment]
Good idea, what about this:

```
+ test input
- {reload} reply one
- {reload} reply two
- reply three
```

Makes for a more logical syntax and also allows to select which replies are reloaded. Same with {keep} but they are reloaded once all replies have been exhausted.

**Comment by silentrob** [comment]
This issue is loosely related to GH-234 and really boils down to how replies are exhausted and used. This was the idea we are looking at implementing:
```
  // keep = ['keep', 'exhaust']
  // order = ['random', 'ordered']

  // verbose
  + {keep=keep, order=random} test random
    
  // shorthand
  + {exhaust, random} test random
  + {keep, ordered} test random

  // shorthand separate syntax
  + {exhaust} {random} test random
  + {keep} {ordered} test random

  // parser error
  + {keep, ordered, random} test random
```
This should also be available on the topic and by global option to set the default values.

**Comment by silentrob** [comment]
This is now in for v1
