### ISSUE TITLE
Evaluate replacing MongoDB with MySQL

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#209]
This is for selfish reasons to play nicer with Slack.

**Comment by deedubs** [comment]
I would love to see pluggable backends

**Comment by mariusursache** [comment]
@silentrob, what about replacing LevelDB with a non-file-based DB (we are having problems with new deploys on AWS). Actually, Dan’s suggestion is great—allow devs to plug in their preferred databases. What are the pros/cons on that?

**Comment by ganarajpr** [comment]
Can you explain the need for a DB at all ? Or if it is part of a documentation somewhere - that would be helpful as well ?

**Comment by Lewwwk** [comment]
@mariusursache fyi, we are running a t2.micro and have moved the level db to a /shared directory specified by an environment variable. Can confirm that the leveldb now persists.

As for switching db's - i too would prefer the ability for ss to work with any existing/provided db. If enabled for mongo and mysql, then perhaps then the community could create specific interfaces for different flavours of db.

**Comment by karovski** [comment]
It would be really awesome if we can have a pluggable end point for the DB(s). I was close to developing something like that a while ago and was thinking on starting with support for providing modules to SS that export the most common db operations (SCRUD stuff...) and go from there.

**Comment by deedubs** [comment]
https://github.com/modella/modella is interesting in that it support MongoDB and leveldb officially and has a mysql plugin contributed by the community

https://github.com/modella/modella/wiki/List-of-Modella-Plugins#adapter-sync-layer-plugins

**Comment by silentrob** [comment]
Nice find @deedubs that looks promising. I'm curious about how the schema is managed.

**Comment by deedubs** [comment]
Scheme management seems OOS of modella :/

**Comment by kennu** [comment]
I am interested running SuperScript on AWS Lambda and wondering if there are any current plans to make the database backends pluggable?

Lambda would also need the engine code to be stateless though, and accept messages asynchronously upon invocation.

**Comment by AndrewMagliozzi** [comment]
+1

**Comment by arnaudsj** [comment]
+1 to AWS Lambda - How can I help decouple the existing back-end?

**Comment by worldofpiggy** [comment]
AWS Lambda would be fantastic

**Comment by silentrob** [comment]
Lambda isn't going to happen as that moves SS into a third party cloud system. MySQL will at some point.

**Comment by silentrob** [comment]
Okay I'm going to close this issue. We have moved levelDB into mongo and will re-evaluate mysql for v2.0.
