### ISSUE TITLE
Remove Message Chunking

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#226]
This functionality can be replicated by exposing mbit as a reply flag

The classic example is 
`My name is Bill. What is your name?` or `My name is Bill, what is your name?`

This should match: 
`+ my name is *` AND `+ * what is your name` in the same flow. 

This can be done by having a force continue tag.

**Comment by benhjames** [comment]
I think we've done all this now @silentrob?

**Comment by silentrob** [comment]
Yep, I took this out a little while back.
