### ISSUE TITLE
Ability to order replies

### ISSUE THREAD

**Issue by Lewwwk** [superscriptjs/superscript#234]
It would be great to be able to force an order of replies in a gambit. 

For example, I may want to progressively educate a user as follows:

```
+ help me
- Helping is something I'm good at. I'd be happy to help. Here are the ways that I can help right now. {@__ways_i_can_help__}
- Here's how I can help. {@__ways_i_can_help__}
- {keep}I'm listening.
```

Rather than random responses, it would be better if those replies could be exhausted in order. Perhaps this could be a gambit flag {ordered} or something like that.

**Comment by silentrob** [comment]
This will be in V1 and should land in 1.0.alpha11
