### ISSUE TITLE
Input types don't work as the doc explains

### ISSUE THREAD

**Issue by espinchi** [superscriptjs/superscript#241]
In https://github.com/silentrob/superscript/wiki/Triggers#input-types, there is a trigger example:

`?:NUM:code * phone *`

That trigger is expected to match the input

> My phone is 415-315 9862.

However, it does not.

In does match the input

> What is your phone number?

I think a few examples would clarify what exactly input types are expected to match. Another example: I expected `ENTY -> color` to match _green_ or _red_, but it doesn't, and I'm not sure what to look for

**Comment by benhjames** [comment]
In v1.0.0, question types will be removed, thus solving this problem!
