### ISSUE TITLE
Support regex triggers too

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#245]
because why not :)

**Comment by silentrob** [comment]
Toying with one of these API's 
```
+ ^RegExp("i like to run (\d+) (miles|km)","i")
- wow <cap1><cap2> is far!


+ /i like to run (\d+) (miles|km)/i
- wow <cap1><cap2> is far!
```

**Comment by dcsan** [comment]
real regexes are powerful but a pain to write. 

RiveScript has that simpler format for regexes that non-techies can use. 
maybe you've already rewritten that part, but JFYI:
https://github.com/aichaos/rivescript-js/issues/79

**Comment by silentrob** [comment]
Yes @dcsan SuperScript was a fork of RiveScript which is why the syntax is already similar. I'm not suggesting abandoning the existing syntax, but rather letting somethings pass though directly for more power users.

The more I think about it, I like
```
+ ^RegExp("i like to run (\d+) (miles|km)","i")
- wow <cap1><cap2> is far!
```
Perhaps we may want to extend this down the road to support other types of parsing:
```
+ ^Trigger("I like to run (*) (miles|km)")
- wow <cap1><cap2> is far!
```
or 
```
+ ChatScript (" like > run ~distance")
- ...
```

**Comment by Lewwwk** [comment]
I like where this is going... particularly with that example @silentrob.

**Comment by tommj** [comment]
FWIW, the text-like syntax is easy to look at and could be easier to remember/contribute to:
`+ /i like to run (\d+) (miles|km)/i`
A visual cue to demark simple parsing (simplified chained regexes: stars, pipes, parentheses, or actual regexes) from [plugins and functions](https://github.com/silentrob/superscript/wiki/Plugins-and-Functions) could be a good thing as long it doesn't interfere with future reply syntax e.g. -^RegExp(.+condition.+)

**Comment by dcsan** [comment]
@tommj you mean rather than wrapping in the ` ^RegExp( ... ) ` just use the `/..../` to denote a regex? 
Agreed, its less noise. 
I guess that makes it harder to use a slash but I think those are illegal in triggers anyway?

**Comment by tommj** [comment]
@dcsan 
Superscript: [**_extra punctuation is removed before being exposed to the engine_**](https://github.com/silentrob/superscript/wiki/Triggers) 
Rivescript: triggers shall not [contain punctuation](https://www.rivescript.com/docs/tutorial) but / is [escaped \/](https://www.rivescript.com/wd/RiveScript#pod2)

The regex function will look clean as long as it contains the name of the exact library being used as superscript currently would as in [issue 136](https://github.com/silentrob/superscript/issues/136):
`+ It is ^OnigRegExp() and ^OnigRegExp()`

**Comment by silentrob** [comment]
Im going to close this idea and maybe revisit it for v2
