### ISSUE TITLE
while files should be .gitignored?

### ISSUE THREAD

**Issue by dcsan** [superscriptjs/superscript#250]
I'm assuming all files like these are generated each `parse` ?
so maybe a .gitignore should also be created by the `bot-init` script?

```
    modified:   data.json
    deleted:    systemDB/000079.log
    modified:   systemDB/CURRENT
    modified:   systemDB/LOG
    modified:   systemDB/LOG.old
    deleted:    systemDB/MANIFEST-000078
    deleted:    telnetFacts/000067.log
    modified:   telnetFacts/CURRENT
    modified:   telnetFacts/LOG
    modified:   telnetFacts/LOG.old
    deleted:    telnetFacts/MANIFEST-000066
```

**Comment by benhjames** [comment]
In v1.0.0 we'll no longer generate any `systemDB` or `telnetFacts` folders since LevelDB is moving to being backed by Mongo.

So the only file generated on parse will be `data.json`, which users are free to either ignore or not.
