### ISSUE TITLE
bin commands 

### ISSUE THREAD

**Issue by dcsan** [superscriptjs/superscript#251]
I noticed `parse` script gets thrown into users path, which seems like it has potential to conflict with something.

```
/usr/local/bin/parse
```

additionally the `cleanup` command, which is arguably more useful, is not available except for in the repo itself. perhaps both of these should stay in the repo but get added to the package.json as scripts?

I have something like this:

```
{
 ...
  "scripts": {
    "cleanup": "./node_modules/superscript/bin/cleanup.js --mongo superscriptDB",
    "parse": "./node_modules/superscript/bin/parse.js -f",
    "watch-ss": "nodemon -e ss ./node_modules/superscript/bin/cleanup.js --mongo superscriptDB"
  }
}

```

`npm run watch-ss` is especially useful when you're just editing scripts and want to restart the bot each time.

**Comment by benhjames** [comment]
I think if users install npm packages globally, they're explicitly taking the risk that they might be adding bin scripts to their `PATH`, so I'm not *too* concerned with this.

If they don't install `superscript` globally, as you say they can just use npm scripts to run the bin scripts. I really like `watch-ss` - that's a good tip!

Btw, in v1.0.0 the `cleanup` script is distributed in the global package so can be used as normal.
