### ISSUE TITLE
removing some of the (NLP) functionality for faster iteration loop?

### ISSUE THREAD

**Issue by dcsan** [superscriptjs/superscript#252]
currently with a very minimal bot, the cleanup/parse time is 13s

i'm not really using a lot of the NLP functions. can this be removed to get to a much faster iteration cycle?
i'm sure you have some other ideas, but meantime this 80:20 would give faster development of a basic bot flow.

```
time npm run cleanup

> dabot@0.0.1 cleanup /Users/dc/dev/rikai/chateditor/ssbot/dabot
> ./node_modules/superscript/bin/cleanup.js --mongo superscriptDB

users is clear
topics is clear
replies is clear
gambits is clear
Time to Process 3.315 seconds
Number of topics 5 parsed.
Number of gambits 14 parsed.
Number of replies 20 parsed.
Number of convos 0 parsed.
Number of Gambits: 0
Number of Replies: 0
Everything imported
npm run cleanup  13.18s user 2.14s system 101% cpu 15.155 total
```

**Comment by benhjames** [comment]
We've re-done a load of the regex logic in v1.0.0 to give parsing improvement times of ~10x faster - hopefully should help you out a great deal!
