### ISSUE TITLE
Previous Capture

### ISSUE THREAD

**Issue by wehriam** [superscriptjs/superscript#256]
**Overview**
- `<pcap>` previous capture functionality does not work as documented.
- See [PR-255](https://github.com/silentrob/superscript/pull/255) for a test implementing the documented functionality.

**Comment by domanhha** [comment]
@wehriam <p1cap1>, <p2cap2> ....  is work for me

**Comment by jimmytuc** [comment]
@domanhha Correct! In complex conversation, use <p1cap1> instead of <pcap1> for simple-single replies.

Thanks,

**Comment by benhjames** [comment]
Since the tests merged in #255 work, I imagine this is resolved - cheers!
