### ISSUE TITLE
Capture stores wordnet conversion rather than original input.

### ISSUE THREAD

**Issue by Lewwwk** [superscriptjs/superscript#264]
In the case of an input capture like this:

```
+ *(1-6)
- ^save(name, <cap>)
```

If passing a wordnet matching input such as: 

> hi

Then `~emohello` is what is captured rather than `hi`.

`hi` is what is expected.

Refs: #262

**Comment by benhjames** [comment]
Will no longer happen in v1.0.0 since we'll no longer replace certain phrases in the message with the wordnet-like tags (e.g. `hello` to `~emohello`), instead exposing them to plugin functions as `message.tags`.
