### ISSUE TITLE
Capturing data

### ISSUE THREAD

**Issue by anhldbk** [superscriptjs/superscript#265]
I've got a script like this one:
![screenshot from 2016-04-20 17-36-14](https://cloud.githubusercontent.com/assets/3270746/14671862/6af53080-071e-11e6-8803-2adc07c85adb.png)

But when I input a message of "i go by something else", the engine can't capture associated data:

![screenshot from 2016-04-20 17-34-34](https://cloud.githubusercontent.com/assets/3270746/14671889/947cd2fa-071e-11e6-98d5-dfe753137aa8.png)

Would you please tell me what wrong is?

**Comment by dcsan** [comment]
good question, from reading the docs here:

https://github.com/silentrob/superscript/wiki/Triggers#variable-length-wildcards

yes that should work up to 4 words... maybe it's a bug.

**Comment by silentrob** [comment]
This seems to work in v1.0.0 and test was added here 7e68843dc76a564cd46e716c3e24c5776beda3d6
