### ISSUE TITLE
Is this project supported anymore ?

### ISSUE THREAD

**Issue by akprats33** [superscriptjs/superscript#271]
I am trying to install and run tests from this project. After running 'npm install' twice I was able to install dependencies. However, running 'npm test' gives errors. I even tried to create a fork, update the dependencies and then create instance of bot from there. There also i get an error as soon as a client sends messages to the bot. The error is -
if (fn === null) throw new Error("Callback was already called.");
Error: Callback was already called.

I am not able to try out this project due to this error. I am running it on OS X EL Captian 10.11.5 , node v 6.2.0.

Please help me out.

**Comment by silentrob** [comment]
Use Node 0.12 or node 0.5.x 

Yes it is still supported and under active development - look at the commit history before asking ridiculous questions. The pre-1.0 tag implies it is still beta. Hit us on the slack questions to get unstuck.

**Comment by akprats33** [comment]
I am sorry that I missed the version. I Should've checked milestone. Failing build on travis confused me to raise this question. It seemed ridiculous to me as well but I wanted to clarify as I had seen a lot on superscript from your blogs. Anyways Thanks.
