### ISSUE TITLE
Error with using {weight=XX}

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [superscriptjs/superscript#275]
I did everything according to instructions http://superscriptjs.com/starter/quickstart
Create new telnet client
And create new rule:
```
   > topic main
     + 1
     - ok

     + * John {weight=80}
     - Hello there

     + hello * {weight=90}
     - Who are you?

   < topic
```

But the rules with tag {weight} does not work.

**Comment by Lewwwk** [comment]
Looks like this is a known issue.  #194

**Comment by cnstntn-kndrtv** [comment]
I repeated the example https://github.com/superscriptjs/superscript/wiki/Topics#weight
What did I do wrong?

**Comment by Lewwwk** [comment]
Nothing. It's a known issue. Have removed it from the docs for the time being.
