### ISSUE TITLE
Multiple arguments or JSON as plugin function argument

### ISSUE THREAD

**Issue by nsaraiya** [superscriptjs/superscript#276]
Rel #57 
## Expected Behavior

Passing in multiple arguments/JSON into a plugin function is not easy. Proposed answer:
- some reply ^addMessageProps({ topic: greeting, mood: happy }) 
  in issue #57 doesn't work due to {} parsing issues.
## Current Behavior

^addMessageProp(key,value)
Repeating this call for every key/value pair becomes cumbersome and is error-prone.
## Possible Solution

Support special syntax for passing in arrays or JSON into the arguments list.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by benhjames** [comment]
Fixed in v1.0.0 - you can now do `^addMessageProps({ topic: "greeting", mood: "happy" })`
