### ISSUE TITLE
Special chars in plugin function arguments cause the function to not get called.

### ISSUE THREAD

**Issue by nsaraiya** [superscriptjs/superscript#277]
Plugin functions don't get called when we pass in some special characters in argument strings. 

For example: some reply ^addMessageProps(greeting, happy) works (i.e. the addMessageProps is called) whereas some reply ^addMessageProps(greeting, happy!) doesn't work. The function addMessageProps is simply not called. 

Need a way to escape special chars when passing strings as function arguments.

One option could be to allow "" as a way of escaping arguments - everything inside "" including commas, etc. gets passed in as a single argument.

**Comment by jelko** [comment]
+1 we need this badly as well!

**Comment by thijskrooswijk** [comment]
@nsaraiya and @jelko – Unfortunately you cannot use special characters and dots. My solution is using encodeurl() or an escape() and encode the dots as well. So you can use special characters and dots in a function and decode it if needed. I hope this is solving your problem.

**Comment by benhjames** [comment]
Fixed in v1.0.0 - you can now use arbitrary parameters like objects or arrays too.

So now you'd use `^addMessageProps("greeting", "happy")`
