### ISSUE TITLE
How can I run '$ parse' command without command line?

### ISSUE THREAD

**Issue by zapbuild** [superscriptjs/superscript#280]
Hi,

I am using superscript to create a chat bot. In chat bot I will provide an interface to add questions and answers for bot. So I need to run 'parse' command manually using command line in Ubuntu. How can I do this using code in node js.

Please help.
Thanks!

**Comment by Lewwwk** [comment]
Sounds like this is something you would do in deploy or startup script on your server if you want to automate it. I still manually run a modified /bin/cleaup.js script when the scripts have been updated in the new deploy.

**Comment by zapbuild** [comment]
Thanks for your reply Michael.
Now I am using https://github.com/silentrob/superscript-editor editor so that I can integrate this editor in my website. My website will have so many users and users can add their own topic and gambits. But when I was testing this (https://github.com/silentrob/superscript-editor) editor, I found much issues. Like (~yes), (~no) are not working. Will you please help me out something.

Thanks!
![gambits](https://cloud.githubusercontent.com/assets/1797589/17852673/0dbcc6c0-6886-11e6-92c6-9caebdfba070.png)

**Comment by Lewwwk** [comment]
@zapbuild as the page you linked says - the editor is out of date and not maintained.  Also, it was meant as a tool to help bot authors create scripts, not as client facing software. Here's some more information also on what to expect with superscript and how it works: https://github.com/superscriptjs/superscript/wiki

**Comment by zapbuild** [comment]
@Lewwwk my requirement is similar. I am creating a chat bot where users can add their own questions and answers. I need superscirpt editor similar like this. Means a better interface so that users can add their script.

**Comment by benhjames** [comment]
So there are two parts to this:

Regarding the editor: #311 may give you some of the direction you need to do this. The idea is that you can store multiple bots on a single database, so you can have one per user etc. Then you'd have to write a tool like superscript-editor to modify the database itself.

Regarding parsing from the command line: I'm not sure what the utility of parsing a script from node is as opposed to the command line, though if there's a good use case we'd definitely consider adding it!
