### ISSUE TITLE
How to store user based questions and answers in superscript?

### ISSUE THREAD

**Issue by zapbuild** [superscriptjs/superscript#281]
Hi
  I am working on chat bot where multiple users(Role:owner) can add/edit/remove their questions and answers for subordinates(Role:travelers). When a traveler questions to chat bot, chat bot should only choose answers added by his User(Role:owner).  

How can I do this? I want something that I will be able to store the user id corresponding to questions/answers in main.ss file.

Please help.

Thanks

**Comment by Lewwwk** [comment]
This is something you would build as normal on the client side - and is beyond the scope of what superscript does.  You can take look at the docs here: https://github.com/superscriptjs/superscript/wiki

**Comment by zapbuild** [comment]
Thanks for your reply Lewwwk

**Comment by benhjames** [comment]
See comment left in #280 - cheers!
