### ISSUE TITLE
Installation issue on Mac 10.11 with Node 6.2.2

### ISSUE THREAD

**Issue by slidenerd** [superscriptjs/superscript#283]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "superscript" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! re2@1.3.3 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the re2@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the re2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs re2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls re2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vivz/Desktop/npm-debug.log
npm ERR! code 1

I did read the other posts similar to this one where you mentioned Node 0.12 and Node 5.5 are the only one supported. Is your support for Node 5.5 public now? or do I have to go down to 0.12?

Thanks for your answer in advance

**Comment by slidenerd** [comment]
I fixed the error with 0.12 thanks, any plans to support the latest versions

**Comment by Lewwwk** [comment]
@slidenerd superscript is fine up to and including node v5
