### ISSUE TITLE
Second reply is always empty

### ISSUE THREAD

**Issue by ingopansa** [superscriptjs/superscript#286]
I have the following main.ss which I compile to a data.json and load into a superscript bot. When querying the bot, the second and any subsequent reply is always empty. To be more specific: the second reply for the same userid is always empty. 

I'm not sure if this is an issue with superscript or something that I'm missing during setup, but I did exactly go through the steps as described in the Getting Started section.

## Expected Behavior
Second and subsequent reply should be hello

## Current Behavior
Second and subsequent reply is empty

## Steps to Reproduce (for bugs)
main.ss
```
+ hi
- hello
```
compiled data.json
```
{
    "topics": {
        "random": {
            "flags": [],
            "keywords": []
        }
    },
    "gambits": {
        "wxXYUTNG": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "isConditional": false,
                "qSubType": false,
                "filter": false
            },
            "replys": [
                "dNb3pWb3"
            ],
            "redirect": null,
            "trigger": "~emohello",
            "raw": "~emohello"
        }
    },
    "convos": {},
    "replys": {
        "dNb3pWb3": "hello"
    },
    "checksums": {
        "./topics/main.ss": "aacbd411d2a88fd818595e0c311357ba1a331be1"
    }
}```

3.
Debug Output of bot when starting
```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pansa/Documents/_fmmly/fmmlybot/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pansa/Documents/_fmmly/fmmlybot/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
  Normalizer Loaded File +0ms { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +3ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +77ms { key: '_contractions', file: 'contractions.txt' }
  Normalizer Loaded File +15ms { key: '_interjections', file: 'interjections.txt' }
  Normalizer Loaded File +31ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +78ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +153ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +3ms
  Normalizer Done Loading files +0ms
  SS:Gambit Normaizer Loaded. +0ms
  mquery count +0ms {} {}
  mquery count +1ms {} {}
  SS:Importer Find or create +70ms random
  mquery findOne +53ms { name: 'random' } { fields: undefined }
Number of Gambits: 0
Number of Replies: 0
  SS:Importer Gambit process: wxXYUTNG +201ms
  RegexReply:Warning Creating a trigger with a word NOT EXPANDED +0ms ~emohello
  SS:Importer Reply process: dNb3pWb3 +671ms
  RegexReply:Warning Creating a trigger with a word NOT EXPANDED +184ms ~emohello
  SS:Importer All gambits for random processed. +179ms
  SS:Importer Add Conditions Added +0ms
  SS:Script Loading Plugin +45ms ./plugins oppisite
  SS:Script Loading Plugin +0ms ./plugins rhymes
  SS:Script Loading Plugin +0ms ./plugins syllable
  SS:Script Loading Plugin +0ms ./plugins letterLookup
  SS:Script Loading Plugin +0ms ./plugins wordLength
  SS:Script Loading Plugin +0ms ./plugins nextNumber
  SS:Script Loading Plugin +0ms ./plugins createFact
  SS:Script Loading Plugin +0ms ./plugins resolveAdjective
  SS:Script Loading Plugin +0ms ./plugins evaluateExpression
  SS:Script Loading Plugin +0ms ./plugins numToRoman
  SS:Script Loading Plugin +1ms ./plugins numToHex
  SS:Script Loading Plugin +0ms ./plugins numToBinary
  SS:Script Loading Plugin +0ms ./plugins numMissing
  SS:Script Loading Plugin +0ms ./plugins numSequence
  SS:Script Loading Plugin +0ms ./plugins addMessageProp
  SS:Script Loading Plugin +0ms ./plugins hasName
  SS:Script Loading Plugin +0ms ./plugins has
  SS:Script Loading Plugin +0ms ./plugins findLoc
  SS:Script Loading Plugin +0ms ./plugins tooAdjective
  SS:Script Loading Plugin +0ms ./plugins usedFor
  SS:Script Loading Plugin +0ms ./plugins resolveFact
  SS:Script Loading Plugin +0ms ./plugins putA
  SS:Script Loading Plugin +0ms ./plugins isA
  SS:Script Loading Plugin +0ms ./plugins colorLookup
  SS:Script Loading Plugin +0ms ./plugins makeChoice
  SS:Script Loading Plugin +0ms ./plugins findMoney
  SS:Script Loading Plugin +0ms ./plugins findDate
  SS:Script Loading Plugin +0ms ./plugins locatedAt
  SS:Script Loading Plugin +0ms ./plugins aquireGoods
  SS:Script Loading Plugin +1ms ./plugins bail
  SS:Script Loading Plugin +0ms ./plugins one
  SS:Script Loading Plugin +0ms ./plugins num
  SS:Script Loading Plugin +0ms ./plugins changetopic
  SS:Script Loading Plugin +0ms ./plugins changefunctionreply
  SS:Script Loading Plugin +0ms ./plugins doSomething
  SS:Script Loading Plugin +0ms ./plugins break
  SS:Script Loading Plugin +0ms ./plugins nobreak
  SS:Script Loading Plugin +0ms ./plugins objparam1
  SS:Script Loading Plugin +0ms ./plugins objparam2
  SS:Script Loading Plugin +0ms ./plugins showScope
  SS:Script Loading Plugin +0ms ./plugins word
  SS:Script Loading Plugin +0ms ./plugins hasFirstName
  SS:Script Loading Plugin +0ms ./plugins getUserId
  SS:Script Loading Plugin +0ms ./plugins getDOW
  SS:Script Loading Plugin +0ms ./plugins getDate
  SS:Script Loading Plugin +0ms ./plugins getDateTomorrow
  SS:Script Loading Plugin +0ms ./plugins getSeason
  SS:Script Loading Plugin +0ms ./plugins getTime
  SS:Script Loading Plugin +0ms ./plugins getGreetingTimeOfDay
  SS:Script Loading Plugin +0ms ./plugins getTimeOfDay
  SS:Script Loading Plugin +0ms ./plugins getDayOfWeek
  SS:Script Loading Plugin +0ms ./plugins getMonth
  SS:Script Loading Plugin +0ms ./plugins save
  SS:Script Loading Plugin +0ms ./plugins hasItem
  SS:Script Loading Plugin +0ms ./plugins get
  SS:Script Loading Plugin +1ms ./plugins createUserFact
  SS:Script Loading Plugin +0ms ./plugins known
  SS:Script Loading Plugin +0ms ./plugins inTopic
  SS:Script Loading Plugin +0ms ./plugins wordnetDefine
  SS:Script Loading Plugin +0ms ./plugins plural
  SS:Script Loading Plugin +0ms ./plugins not
  SS:Script Loading Plugin +0ms ./plugins lowercase
  Normalizer Loaded File +1s { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +1ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +59ms { key: '_contractions', file: 'contractions.txt' }
  Normalizer Loaded File +9ms { key: '_interjections', file: 'interjections.txt' }
  Normalizer Loaded File +31ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +60ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +166ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +3ms
  Normalizer Done Loading files +0ms
  SS:Gambit Normaizer Loaded. +329ms
  mquery count +1s {} {}
  mquery count +1ms {} {}
  Normalizer Loaded File +46ms { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +1ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +48ms { key: '_contractions', file: 'contractions.txt' }
  Normalizer Loaded File +5ms { key: '_interjections', file: 'interjections.txt' }
  Normalizer Loaded File +23ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +42ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +110ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +2ms
  Normalizer Done Loading files +0ms
Number of Gambits: 1
Number of Replies: 1
  SS:Script System Loaded, waiting for replies +298ms
```

4. Debug Output of 1st reply
```
  SS:Script [ New Message - 'mNGnMjuJTqh1gSTcR7juwl3clwh2']- hi +9m
  mquery findOne +9.1m { id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2' } { fields: undefined }
  SS:User Pre-Save Hook +9ms
  SS:Script IN MessageFactory +421ms ~emohello
  SS:Message Creating message from: +1ms ~emohello
  SS:Message fullnames +551ms names []
  SS:Message Fetch List +0ms
  SS:Message fullnames +1ms nouns []
  SS:Message Message +1ms { id: 'svi1exTp',
  facts: 
   { conceptToList: [Function],
     findParentConcepts: [Function],
     db: 
      { breadthFirst: [Function: breadthFirst],
        deepFirst: [Function: deepFirst] },
     level: 
      LevelUP {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: Infinity,
        options: [Object],
        _codec: [Object],
        _status: 'open',
        location: 'botfacts',
        db: [Object],
        createWriteStream: [Function],
        writeStream: [Function] },
     createUserDB: [Function],
     createUserDBWithData: [Function],
     loadFile: [Function] },
  createdAt: 2016-09-09T16:34:28.636Z,
  raw: '~emohello',
  original: 'hi',
  props: {},
  clean: '~emohello',
  dict: { words: [ [Object] ] },
  words: [ '~emohello' ],
  cwords: [ '~emohello' ],
  taggedWords: [ [ '~emohello', 'NN' ] ],
  lemWords: [ '~emohello' ],
  lemString: '~emohello',
  posString: 'NN',
  qtype: '',
  qSubType: '',
  isQuestion: false,
  sentiment: 0,
  nouns: [ '~emohello' ],
  names: [],
  list: [],
  adjectives: [],
  adverbs: [],
  verbs: [],
  pnouns: [],
  pronouns: [],
  compareWords: [],
  numbers: [],
  compare: false,
  date: null,
  cNouns: [ '~emohello' ],
  numericExp: false,
  halfNumericExp: false,
  entities: [ '~emohello' ] }
  SS:User getTopic +3ms random
  SS:Topics Token And Stem Words +1ms [ 'emohello' ]
  SS:Topics Score Inner +0ms []
  SS:Topics Topic Score +1ms []
  mquery find +987ms {} { fields: undefined }
  SS:GetReply Topics to check +4ms [ 'random' ]
  mquery findOne +6ms { _id: 57d2e2702e2341855321bfe1 } { fields: undefined }
  mquery find +3ms { _id: { '$in': [ 57d2e2702e2341855321bfe2 ] } } { fields: undefined }
  SS:GetReply Checking for conditions in random +8ms
  SS:User Pre-Save Hook +1ms
  SS:GetReply Topic findMatch random +1ms
  SS:Common Looking back Topic +0ms 57d2e2702e2341855321bfe1
  mquery findOne +6ms { _id: 57d2e2702e2341855321bfe1 } { fields: { gambits: 1 } }
  mquery find +1ms { _id: { '$in': [ 57d2e2702e2341855321bfe2 ] },
  isCondition: false } { fields: undefined }
  mquery find +2ms { _id: { '$in': [ 57d2e2702e2341855321bfe3 ] } } { fields: undefined }
  SS:Common Try to match (clean)'~emohello' against ~emohello (~emohello) +6ms
  SS:Common Try to match (lemma)'~emohello' against ~emohello (~emohello) +0ms
  SS:Common Match found +1ms { _id: 57d2e2702e2341855321bfe2,
  trigger: '~emohello',
  input: '~emohello',
  __v: 1,
  redirect: '',
  replies: 
   [ { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' } ],
  filter: '',
  qSubType: '',
  qType: '',
  isCondition: false,
  isQuestion: false,
  id: 'wxXYUTNG' } [ '~emohello', index: 0, input: '~emohello' ]
  SS:Common Match found '~emohello' in topic 'random' +1ms
  SS:GetReply match itor +0ms { _id: 57d2e2702e2341855321bfe2,
  trigger: '~emohello',
  input: '~emohello',
  __v: 1,
  redirect: '',
  replies: 
   [ { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' } ],
  filter: '',
  qSubType: '',
  qType: '',
  isCondition: false,
  isQuestion: false,
  id: 'wxXYUTNG' }
  mquery findOne +5ms { _id: 57d2e2702e2341855321bfe2 } { fields: undefined }
  mquery find +1ms { _id: { '$in': [ 57d2e2702e2341855321bfe3 ] } } { fields: undefined }
  mquery findOne +26ms { gambits: { '$in': [ '57d2e2702e2341855321bfe2' ] } } { fields: undefined }
  SS:GetReply filterByFunction Results +30ms [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2 } ]
  SS:GetReply filterRepliesBySeen +1ms [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2 } ]
  mquery findOne +4ms { name: 'random' } { fields: undefined }
  SS:GetReply Bucket +2ms [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2 } ]
  SS:ProcessTags Depth +1ms 0
  SS:ProcessTags Reply 'hello' +0ms
  SS:User setTopic +0ms random
  SS:ProcessHelpers New Topic +0ms undefined
  SS:User Pre-Save Hook +2ms
  SS:ProcessTags Calling back with +2ms { id: 'dNb3pWb3',
  stars: [],
  topic: 'random',
  reply: 
   { _id: 57d2e2702e2341855321bfe3,
     reply: 'hello',
     parent: '57d2e2702e2341855321bfe2',
     __v: 0,
     gambits: [],
     filter: '',
     keep: false,
     id: 'dNb3pWb3' },
  trigger: '~emohello',
  trigger_id: 'wxXYUTNG',
  trigger_id2: 57d2e2702e2341855321bfe2 }
  SS:GetReply ProcessTags Return +1ms { id: 'dNb3pWb3',
  stars: [],
  topic: 'random',
  reply: 
   { _id: 57d2e2702e2341855321bfe3,
     reply: 'hello',
     parent: '57d2e2702e2341855321bfe2',
     __v: 0,
     gambits: [],
     filter: '',
     keep: false,
     id: 'dNb3pWb3' },
  trigger: '~emohello',
  trigger_id: 'wxXYUTNG',
  trigger_id2: 57d2e2702e2341855321bfe2,
  props: {},
  matched_reply_string: 'hello',
  matched_topic_string: 'random' }
  SS:GetReply MatchSet +1ms true [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2,
    props: {},
    matched_reply_string: 'hello',
    matched_topic_string: 'random' } ]
  SS:GetReply afterHandle +1ms { replyId: 57d2e2702e2341855321bfe3,
  props: {},
  clearConvo: false,
  topicName: 'random',
  minMatchSet: 
   [ { topic: 'random',
       input: '~emohello',
       reply: 'hello',
       output: 'hello' } ],
  string: 'hello',
  subReplies: [],
  stars: [],
  breakBit: undefined }
  SS:Message Creating message from: +0ms hello
  SS:Message fullnames +2ms names []
  SS:Message Fetch List +0ms
  SS:Message fullnames +1ms nouns []
  SS:Message Message +0ms { id: 'DUTG6r5e',
  replyId: 57d2e2702e2341855321bfe3,
  facts: 
   { conceptToList: [Function],
     findParentConcepts: [Function],
     db: 
      { breadthFirst: [Function: breadthFirst],
        deepFirst: [Function: deepFirst] },
     level: 
      LevelUP {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: Infinity,
        options: [Object],
        _codec: [Object],
        _status: 'open',
        location: 'botfacts',
        db: [Object],
        createWriteStream: [Function],
        writeStream: [Function] },
     createUserDB: [Function],
     createUserDBWithData: [Function],
     loadFile: [Function] },
  createdAt: 2016-09-09T16:34:29.258Z,
  raw: 'hello',
  original: undefined,
  props: {},
  clean: 'hello',
  dict: { words: [ [Object] ] },
  words: [ 'hello' ],
  cwords: [ 'hello' ],
  taggedWords: [ [ 'hello', 'UH' ] ],
  lemWords: [ 'hello' ],
  lemString: 'hello',
  posString: 'UH',
  qtype: '',
  qSubType: '',
  isQuestion: false,
  sentiment: 0,
  nouns: [],
  names: [],
  list: [],
  adjectives: [],
  adverbs: [],
  verbs: [],
  pnouns: [],
  pronouns: [],
  compareWords: [],
  numbers: [],
  compare: false,
  date: null,
  cNouns: [],
  numericExp: false,
  halfNumericExp: false,
  entities: [] }
  SS:User Updating History +5ms
  mquery findOne +19ms { name: 'random' } { fields: undefined }
  SS:User setTopic Complete +3ms
  SS:User Pre-Save Hook +1ms
  SS:User Pre-Save Hook +7ms
  SS:Script null +0ms { lastMessageSentAt: 2016-09-09T16:34:29.262Z,
  pendingTopic: null,
  conversationState: {},
  __v: 1,
  id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2',
  currentTopic: 'random',
  status: 0,
  conversation: 1,
  volley: 0,
  rally: 0,
  _id: 57d2e4942e2341855321bfe4,
  __history__: 
   { stars: [ [] ],
     topic: [ 'random' ],
     reply: [ [Object] ],
     input: [ [Object] ] } }
  SS:Script Update and Reply to user 'mNGnMjuJTqh1gSTcR7juwl3clwh2' +2ms { replyId: 57d2e2702e2341855321bfe3,
  createdAt: 2016-09-09T16:34:29.258Z,
  string: 'hello',
  topicName: 'random',
  subReplies: [],
  debug: 
   { user_id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2',
     raw_input: 'hi',
     normalized_input: '~emohello',
     matched_gambit: [ [Object] ],
     final_output: 'hello',
     timestamp: 2016-09-09T16:34:28.636Z } }
  SS:Script [ Final Reply - 'mNGnMjuJTqh1gSTcR7juwl3clwh2']- 'hello' +0ms
processQueue() - bot reply: {"replyId":"57d2e2702e2341855321bfe3","createdAt":"2016-09-09T16:34:29.258Z","string":"hello","topicName":"random","subReplies":[],"debug":{"user_id":"mNGnMjuJTqh1gSTcR7juwl3clwh2","raw_input":"hi","normalized_input":"~emohello","matched_gambit":[{"topic":"random","input":"~emohello","reply":"hello","output":"hello"}],"final_output":"hello","timestamp":"2016-09-09T16:34:28.636Z"}}
```

5. Debug Output of 2nd (and any subsequent) reply
```
  SS:Script [ New Message - 'mNGnMjuJTqh1gSTcR7juwl3clwh2']- hi +1m
  mquery findOne +1.0m { id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2' } { fields: undefined }
  SS:Script IN MessageFactory +245ms ~emohello
  SS:Message Creating message from: +0ms ~emohello
  SS:Message fullnames +4ms names []
  SS:Message Fetch List +0ms
  SS:Message fullnames +0ms nouns []
  SS:Message Message +0ms { id: 'CBLjMluN',
  facts: 
   { conceptToList: [Function],
     findParentConcepts: [Function],
     db: 
      { breadthFirst: [Function: breadthFirst],
        deepFirst: [Function: deepFirst] },
     level: 
      LevelUP {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: Infinity,
        options: [Object],
        _codec: [Object],
        _status: 'open',
        location: 'botfacts',
        db: [Object],
        createWriteStream: [Function],
        writeStream: [Function] },
     createUserDB: [Function],
     createUserDBWithData: [Function],
     loadFile: [Function] },
  createdAt: 2016-09-09T16:35:31.913Z,
  raw: '~emohello',
  original: 'hi',
  props: {},
  clean: '~emohello',
  dict: { words: [ [Object] ] },
  words: [ '~emohello' ],
  cwords: [ '~emohello' ],
  taggedWords: [ [ '~emohello', 'NN' ] ],
  lemWords: [ '~emohello' ],
  lemString: '~emohello',
  posString: 'NN',
  qtype: '',
  qSubType: '',
  isQuestion: false,
  sentiment: 0,
  nouns: [ '~emohello' ],
  names: [],
  list: [],
  adjectives: [],
  adverbs: [],
  verbs: [],
  pnouns: [],
  pronouns: [],
  compareWords: [],
  numbers: [],
  compare: false,
  date: null,
  cNouns: [ '~emohello' ],
  numericExp: false,
  halfNumericExp: false,
  entities: [ '~emohello' ] }
  SS:User getTopic +2ms random
  SS:Topics Token And Stem Words +0ms [ 'emohello' ]
  SS:Topics Score Inner +0ms []
  SS:Topics Topic Score +1ms []
  mquery find +251ms {} { fields: undefined }
  SS:Topics Last reply:  +2ms hello 57d2e2702e2341855321bfe3 undefined
  mquery findOne +2ms { _id: 57d2e2702e2341855321bfe3 } { fields: undefined }
  mquery findOne +2ms { _id: 57d2e2702e2341855321bfe3 } { fields: undefined }
  mquery find +1ms { _id: { '$in': [ 57d2e2702e2341855321bfe2 ] } } { fields: undefined }
  SS:Common Walk +4ms { _id: 57d2e2702e2341855321bfe3,
  reply: 'hello',
  parent: 
   { _id: 57d2e2702e2341855321bfe2,
     trigger: '~emohello',
     input: '~emohello',
     __v: 1,
     redirect: '',
     replies: [ '57d2e2702e2341855321bfe3' ],
     filter: '',
     qSubType: '',
     qType: '',
     isCondition: false,
     isQuestion: false,
     id: 'wxXYUTNG' },
  __v: 0,
  gambits: [],
  filter: '',
  keep: false,
  id: 'dNb3pWb3' }
  SS:GetReply Topics to check +1ms [ undefined, 'random' ]
  mquery findOne +2ms { _id: 57d2e2702e2341855321bfe3 } { fields: undefined }
  SS:GetReply Conversation Reply Thread +1ms { _id: 57d2e2702e2341855321bfe3,
  reply: 'hello',
  parent: '57d2e2702e2341855321bfe2',
  __v: 0,
  gambits: [],
  filter: '',
  keep: false,
  id: 'dNb3pWb3' }
  SS:Common Looking back at Conversation +0ms 57d2e2702e2341855321bfe3
  mquery findOne +2ms { _id: 57d2e2702e2341855321bfe3 } { fields: { gambits: 1 } }
  mquery findOne +1ms { _id: 57d2e2702e2341855321bfe1 } { fields: undefined }
  mquery find +1ms { _id: { '$in': [ 57d2e2702e2341855321bfe2 ] } } { fields: undefined }
  SS:GetReply Checking for conditions in random +4ms
  SS:User Pre-Save Hook +1ms
  SS:GetReply Topic findMatch random +0ms
  SS:Common Looking back Topic +1ms 57d2e2702e2341855321bfe1
  mquery findOne +3ms { _id: 57d2e2702e2341855321bfe1 } { fields: { gambits: 1 } }
  mquery find +0ms { _id: { '$in': [ 57d2e2702e2341855321bfe2 ] },
  isCondition: false } { fields: undefined }
  mquery find +2ms { _id: { '$in': [ 57d2e2702e2341855321bfe3 ] } } { fields: undefined }
  SS:Common Try to match (clean)'~emohello' against ~emohello (~emohello) +3ms
  SS:Common Try to match (lemma)'~emohello' against ~emohello (~emohello) +0ms
  SS:Common Match found +0ms { _id: 57d2e2702e2341855321bfe2,
  trigger: '~emohello',
  input: '~emohello',
  __v: 1,
  redirect: '',
  replies: 
   [ { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' } ],
  filter: '',
  qSubType: '',
  qType: '',
  isCondition: false,
  isQuestion: false,
  id: 'wxXYUTNG' } [ '~emohello', index: 0, input: '~emohello' ]
  SS:Common Match found '~emohello' in topic 'random' +0ms
  SS:GetReply match itor +0ms { _id: 57d2e2702e2341855321bfe2,
  trigger: '~emohello',
  input: '~emohello',
  __v: 1,
  redirect: '',
  replies: 
   [ { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' } ],
  filter: '',
  qSubType: '',
  qType: '',
  isCondition: false,
  isQuestion: false,
  id: 'wxXYUTNG' }
  mquery findOne +2ms { _id: 57d2e2702e2341855321bfe2 } { fields: undefined }
  mquery find +1ms { _id: { '$in': [ 57d2e2702e2341855321bfe3 ] } } { fields: undefined }
  mquery findOne +1ms { gambits: { '$in': [ '57d2e2702e2341855321bfe2' ] } } { fields: undefined }
  SS:GetReply filterByFunction Results +4ms [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2 } ]
  SS:GetReply filterRepliesBySeen +0ms [ { id: 'dNb3pWb3',
    stars: [],
    topic: 'random',
    reply: 
     { _id: 57d2e2702e2341855321bfe3,
       reply: 'hello',
       parent: '57d2e2702e2341855321bfe2',
       __v: 0,
       gambits: [],
       filter: '',
       keep: false,
       id: 'dNb3pWb3' },
    trigger: '~emohello',
    trigger_id: 'wxXYUTNG',
    trigger_id2: 57d2e2702e2341855321bfe2 } ]
  mquery findOne +1ms { name: 'random' } { fields: undefined }
  SS:GetReply --------------- FILTER SEEN ---------------- +1ms
  SS:GetReply repIndex +0ms 57d2e2702e2341855321bfe3
  SS:GetReply pastGambit.replyId +0ms 57d2e2702e2341855321bfe3
  SS:GetReply pastInput id +0ms 57d2e2702e2341855321bfe2
  SS:GetReply current inputId +0ms 57d2e2702e2341855321bfe2
  SS:GetReply reply.keep +0ms false
  SS:GetReply currentTopic.keep +0ms false
  SS:GetReply Already Seen +0ms { _id: 57d2e2702e2341855321bfe3,
  reply: 'hello',
  parent: '57d2e2702e2341855321bfe2',
  __v: 0,
  gambits: [],
  filter: '',
  keep: false,
  id: 'dNb3pWb3' }
  SS:GetReply Bucket +0ms []
  SS:GetReply true +1ms
  SS:GetReply MatchSet +0ms null [ undefined ]
  SS:GetReply afterHandle +0ms { replyId: null,
  props: {},
  clearConvo: false,
  topicName: null,
  minMatchSet: [],
  string: '',
  subReplies: [],
  stars: null,
  breakBit: null }
  SS:Message Creating message from: +0ms 
  SS:Message Callback Early, empty msg +0ms
  SS:User Updating History +1ms
  mquery findOne +3ms { name: null } { fields: undefined }
  SS:User Pre-Save Hook +1ms
  SS:User Pre-Save Hook +13ms
  SS:Script null +1ms { _id: 57d2e4942e2341855321bfe4,
  id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2',
  currentTopic: null,
  status: 0,
  conversation: 2,
  volley: 0,
  rally: 0,
  __v: 2,
  conversationState: {},
  pendingTopic: null,
  lastMessageSentAt: 2016-09-09T16:35:31.943Z,
  __history__: 
   { stars: [ null, [] ],
     topic: [ 'random', 'random' ],
     reply: [ {}, [Object] ],
     input: [ [Object], [Object] ] } }
  SS:Script Update and Reply to user 'mNGnMjuJTqh1gSTcR7juwl3clwh2' +3ms { replyId: null,
  createdAt: 2016-09-09T16:35:31.958Z,
  string: '',
  topicName: null,
  subReplies: [],
  debug: 
   { user_id: 'mNGnMjuJTqh1gSTcR7juwl3clwh2',
     raw_input: 'hi',
     normalized_input: '~emohello',
     matched_gambit: [],
     final_output: undefined,
     timestamp: 2016-09-09T16:35:31.913Z } }
  SS:Script [ Final Reply - 'mNGnMjuJTqh1gSTcR7juwl3clwh2']- '' +1ms
processQueue() - bot reply: {"replyId":null,"createdAt":"2016-09-09T16:35:31.958Z","string":"","topicName":null,"subReplies":[],"debug":{"user_id":"mNGnMjuJTqh1gSTcR7juwl3clwh2","raw_input":"hi","normalized_input":"~emohello","matched_gambit":[],"timestamp":"2016-09-09T16:35:31.913Z"}}
```

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* node -v: v6.3.1
* npm -v: 3.10.3
* package.json 
```
{
  "name": "XXX",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "debug": "~2.0.0",
    "mongoose": "3.8.24",
    "request": "^2.74.0",
    "sfacts": "latest",
    "superscript": "latest"
  }
}
```

**Comment by Lewwwk** [comment]
I think what you looking for is the {keep} flag to persist replies. By default, superscript will exhaust replies once they have been used for the user.

https://github.com/superscriptjs/superscript/wiki/Conversations#complex-conversations

**Comment by ingopansa** [comment]
yea, that totally solved the issue. I thought it would behave the same way as it does with rivescript, where it basically does not store a state on which replies have been used and then discards them. Thanks!

**Comment by silentrob** [comment]
Thanks @Lewwwk for jumping in on this!
