### ISSUE TITLE
How to change superscript default tables name?

### ISSUE THREAD

**Issue by zapbuild** [superscriptjs/superscript#287]
Hi
When Superscript is installed it creates topics, gambit and replies tables in the database. Can I change these table names to topic_user_1,gambits_user_2 and so on. 
Please help.
Thanks!

**Comment by Lewwwk** [comment]
@zapbuild you are probably better off asking questions in the slack community: http://superscript-slackin.herokuapp.com

Currently superscript defines the schema directly. PR's that make it easier to piggyback an external schema would certainly be welcome!

**Comment by benhjames** [comment]
#311 will address this by prefixing collections with "ss_" and adding multitenancy, so closing this issue for discussion to go there instead - cheers!
