### ISSUE TITLE
I already have a User model, So I want to change the User schema name 

### ISSUE THREAD

**Issue by enraiser** [superscriptjs/superscript#288]
I am using keystoneJS, which already has schema called User. 
So I am forced to modify the lib/usesr.js and rename User to User2

>   try {
>     return mongoose.model("User2", userSchema);
>   } catch(e) {
>     return mongoose.model("User2");
>   }

**Comment by Lewwwk** [comment]
Currently superscript defines the schema directly. PR's that make it easier to piggyback an external schema would certainly be welcome! 

Refs: #287

**Comment by benhjames** [comment]
#311 will address this by prefixing collections with "ss_", so closing this issue for discussion to go there instead - cheers!
