### ISSUE TITLE
Every page is different context

### ISSUE THREAD

**Issue by enraiser** [superscriptjs/superscript#289]
In my case every page of my site has different context. 

there are two option, 

(1) assign each page as one topic and programatically set the topic. I dont know how I can do that.

(2) I  set different DB for each page and prepare different SS for each page. but the issue there is User created by superscript will get duplicated on each page. and may loose the general answers.  I am not sure about this  too.

**Comment by Lewwwk** [comment]
@enraiser this isn't really an issue - you are better off asking questions in the slack community: http://superscript-slackin.herokuapp.com

In general, you may wish to read the documentation as well https://github.com/superscriptjs/superscript/wiki and in particular the section on topics: https://github.com/superscriptjs/superscript/wiki/Topics

**Comment by enraiser** [comment]
ok me and @zapbuild worked out on this, issue and suggested this patch .

https://github.com/superscriptjs/superscript/issues/291

**Comment by benhjames** [comment]
Hopefully the answer I just gave in #291 will help you!
