### ISSUE TITLE
v120 tools needed for Windows hence superscript install fails

### ISSUE THREAD

**Issue by slidenerd** [superscriptjs/superscript#294]
I am using Windows 10 with an x64 architecture and trying to install superscript. I never managed to install superscript since the last month. I know this issue is related to node-gyp and v120 wont work as I have Visual Studio 2015 on my end which I believe is v140. I have also been tracking your issue where you guys seem to work node-re2 Does that mean fixing node-re2 dependency will resolve the problems below because I plan to use superscript on a server environment and would certainly prefer not installing Visual Studio on the server. Thank you for your suggestions in advance

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120'
) cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by
selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Program Files\nodejs\node_modules\superscript\node_modules\
re2\build\re2.vcxproj]
```

**Comment by benhjames** [comment]
Fixed in v1.0.0 which will no longer require any build tools (or RE2).
