### ISSUE TITLE
Fail to install v1.0.0 ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#304]
```
cd MY_PROJECT
npm install git@github.com:Samurais/superscript.git#v1.0.0

```

## Expected Behavior
It should install v1.0.0 successfully. 

## Current Behavior
```
$ npm install
npm WARN philly-logic@1.0.0 No repository field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! path philly-logic/node_modules/superscript/lib/bin/cleanup.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'philly-logic/node_modules/superscript/lib/bin/cleanup.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'philly-logic/node_modules/superscript/lib/bin/cleanup.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     chatbot-mvp/philly-logic/npm-debug.log
```

## Possible Solution
It is not a ss issue, it seems to be npm fail to create folders with version number.

## Steps to Reproduce (for bugs)
1. create empty project
```
mkdir foo
cd foo
npm init
```

2. Install ss
```
npm install git@github.com:Samurais/superscript.git#v1.0.0
```

If installing ss by default version, 
```
npm install git@github.com:Samurais/superscript.git
```
The work is done, but it just installs v0.12.0.

## Context
Try the latest version.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Mac OSX
* Link to your project:

**Comment by Samurais** [comment]
Get a workaround, use this module as submodule. 
```
[submodule "myproj/superscript"]
        path = myproj/superscript
        url = git@github.com:Samurais/superscript.git
        branch = v1.0.0
```

**Comment by benhjames** [comment]
It looks like `npm install git@github.com:Samurais/superscript.git#v1.0.0` should now work with your permission change on the cleanup file, no need to use submodules.
