### ISSUE TITLE
[v1.0.0] require topic name in .ss 

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#308]
Define a topic without a topic name.

![image](https://cloud.githubusercontent.com/assets/3538629/20352284/a28c78a4-ac51-11e6-9bd9-6df0f9cd58dc.png)

Process it with  ss-parser@v1.0.0 - alpha2.

## Expected Behavior
save data.json.

## Current Behavior
```
$ lib/bin/parse.js -f
undefined:3095
      throw peg$buildStructuredError(
      ^
SyntaxError: Expected " " or ":" but "\n" found.
    at peg$buildStructuredError (eval at compile (superscript/node_modules/pegjs/lib/compiler/index.js:67:37), <anonymous>:507:14)
    at Object.peg$parse [as parse] (eval at compile (/superscript/node_modules/pegjs/lib/compiler/index.js:67:37), <anonymous>:3095:13)
    at parseContents (superscript/node_modules/ss-parser/lib/parseContents.js:256:23)
    at /superscript/node_modules/ss-parser/lib/index.js:36:38
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

## Possible Solution
If define the topic as below, it works well.

![image](https://cloud.githubusercontent.com/assets/3538629/20352275/9cb39a66-ac51-11e6-8381-98443ea518de.png)

The anonymous topic is defined as random topic, it should be supported in v1.0.0.

## Your Environment

* Version used: v1.0.0@latest
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by benhjames** [comment]
On topics with no name: you can just put gambits/replies into the top-level script with no topics at all, and they’ll automatically be added into the random topic.

There’s no obligation to wrap everything in a topic, though of course, you can if you want, but they need a name (and if you really want to put gambits in the random topic within the topic syntax, you can just use the name random).
