### ISSUE TITLE
Confusion regarding .tbl files from ChatScript

### ISSUE THREAD

**Issue by RichardB122** [superscriptjs/superscript#313]
Hi, I would like to better understand how to use .tbl files in my chatbots. I haven't had much experience with ChatScript and so I don't have a full understanding of how it works. I looked for documentation, but couldn't find any, I also looked through an old issue which seemed provide some insight, but didn't answer everything. https://github.com/superscriptjs/superscript/issues/110

First what I want to confirm is that .tbl files could be used to create additional information that would be accessed in a similar way to wordnet and conceptnet within the patterns themselves. It also seemed like in the issue that implementing .tbl files overrode those libraries although I am not sure.

I would like to use .tbl files to add additonal functionality but not take away from the wordnet and conceptnet libraries. One of the main uses I would like this for is for home automation. I would like to be able to create a new category with the names of all the lights in my house that could show up in patterns like <lights> or ~lights. I am also not sure whether a .tbl files list concepts, words or both.

Also I think we really need an article that documents how to implement .tbl files into a chatbot as it is probably something that many people could benefit from. I'd be fine with drafting some documentation for this myself, but I do need someone to explain it to me.

Thanks for all your hard work on this project.

**Comment by silentrob** [comment]
This has been addressed in the 1.0 wiki.
