### ISSUE TITLE
How can i display the reminder message without user input i.e without affecting normal conversation with chatbot? 

### ISSUE THREAD

**Issue by Nimmi-Ghetia** [superscriptjs/superscript#321]
I want to create a reminder in chatbot which will check every minute if the required time is arrived or not. If yes, then display it to user but user should be able to do conversation until that time arrives. Where should i call such a function? Is there any other idea for creating a reminder?

Versions are mentioned below:
node v 6.9.2
npm v 3.10.9
Ubuntu 16.04

**Comment by benhjames** [comment]
I'd recommend adding a message prop in the reply with the required time to send the reminder, and then handling it in the client (express/telnet etc) i.e. `setTimeout(/* function to call bot again here */, reply.props.timeout)`. Note that there may be weird issues with modifying conversation state doing it this way.

Or if you know ahead of time what the reminder message is going to be, then `setTimeout(/* function to send reply.props.reminderMessage to user */, reply.props.timeout)` may be more useful.
