### ISSUE TITLE
cleanup expects MONGO_URI, deploy to Heroku uses MONGODB_URI

### ISSUE THREAD

**Issue by bmann** [superscriptjs/superscript#322]
You can run commands with the running bot on Heroku directly.

For example, `heroku run node_modules/.bin/cleanup`

Currently, this throws an error, starting with "MongoError: failed to connect to server…".

This happens because cleanup has `process.env.MONGO_URI`, and mongoLab addon uses MONGODB_URI by default.

Work around: edit your Heroku environment that copies your MONGODB_URI to a new config var MONGO_URI.

Suggested fix: add an additional `|| process.env.MONGODB_URI` to the mongoURI line in cleanup.

**Comment by benhjames** [comment]
Nice catch! Will change when I get a moment. :smile:

**Comment by benhjames** [comment]
Fixed in v1.0.6 - sorry for the wait!
