### ISSUE TITLE
Topics and conversations

### ISSUE THREAD

**Issue by priyendumori** [superscriptjs/superscript#324]
I'm facing difficulty what topics to keep and how to write gambits for conversations.

It would be really easy to understand and experiment if i had some demo code or some test bot's source code for reference or any other kind of help that can be useful.

I just want a basic flowing conversation.
I hope somebody can help me. Thank you.

**Comment by benhjames** [comment]
There are a few examples you could look at from the top of my head:

You may like to check out @silentrob's Brit bot (https://github.com/silentrob/brit) which is a really great example of a bot with lots of content.

Alternatively, have a look at the scripts in the `test/fixtures/*` directory in this repo to see some test scripts. There's also a couple basic ones in the `example` folder!

Hopefully that's enough to get you started - perhaps we should write a comprehensive script to show off all the features you can use.

And of course the Wiki has a load of examples and documentation too.

**Comment by priyendumori** [comment]
@silentrob's brit bot was very helpful thank you.
But i am facing difficulty with it which i have posted as another issue named "problem in loading concepts and tables". Hope somebody can help me with that.

**Comment by Nordes** [comment]
@priyendumori In the end, were you able to make it working?
