### ISSUE TITLE
Error parsing bot script: Error whilst processing file: ./chat/animals.ss

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#327]
make a simple topic and parse it.

```
> topic:system:keep animals (animals)

+ hello
- hi

< topic
```

Get an error from console.

## Expected Behavior

Generate data.json without error.

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/3538629/24041426/5d94f7d4-0b48-11e7-8a29-3de5b10fa7bc.png)

it works well when changing to below.
```
> topic animals (animals)

+ hello
- hi
< topic

```

So, it seems keep and system is not supported well.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ss@1.0.6, ss-parser@1.0.1
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): NodeJS v7.1.6
* Server type and version:  
* Operating System and version: Mac OSX
* Link to your project:

**Comment by benhjames** [comment]
We changed the syntax slighly in v1 to make topic options be consistent with trigger and reply options. You'll now want to do:

```
> topic {keep} {system} animals (animals)
```

**Comment by Samurais** [comment]
I see, that is great!

**Comment by silentrob** [comment]
Docs have been updated today. Thanks @Lewwwk for that.
