### ISSUE TITLE
how to add comments in superscript 

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#328]
# Description
Sometimes, I would like to add comment in the script.  A common usage is the maintainer information.

# Solution
Does superscript support some lines as comment?
Such as 
```
" [design] foo 
" [maintainer] bar
" [date] 2017-03-18

> topic t1 {keep} {system} (animals)
 
+ hello
- hi

<
```

**Comment by silentrob** [comment]
Yes both single line and multi line comments are supported.
`// this is a comment`
```
/*
This is also a comment
*/
```

**Comment by silentrob** [comment]
I noticed I litter the examples in the wiki with comments but don't actually document them specifically.

**Comment by silentrob** [comment]
Wiki updated.
