### ISSUE TITLE
Parsing error: Gambit redirects in topic

### ISSUE THREAD

**Issue by simonwjackson** [superscriptjs/superscript#332]
```js
+ __greeting__
- Hi there!

> topic introduce
  + hi
  - {@__greeting__}
< topic
```
Works correctly outside a topic but produces an empty string when triggered inside a topic.
> Note: Sub replies continue to parse correctly

## Expected Behavior
```js
{ string: 'Hi there!' }
```

## Current Behavior
```js
{ string: '' }
```

**Comment by benhjames** [comment]
`{@__trigger__}` is an inline redirect so it only searches the topic it's within. You'll want to use `topicRedirect("introduce", "__greeting__")` to search another topic! 😃
