### ISSUE TITLE
processing user input and passing it to custom function 

### ISSUE THREAD

**Issue by meghasoni** [superscriptjs/superscript#334]
example 1 :  
 
 + redirect *1  *2  
  - ^customfunction(&lt;cap1&gt;,&lt;cap2&gt;)  

example 2 :  Process the complete sentence and pass to the custom function
 
 +  *[complete sentence give by the user]
  - ^customfunction(&lt;cap&gt;)  

Please help in creating the gambit

**Comment by benhjames** [comment]
You can access the full original message in the custom plugin with `this.message.raw`, and then call it without any `cap` parameters i.e. `^customfunction()` :)

**Comment by meghasoni** [comment]
@benhjames  thanks for your help..
