### ISSUE TITLE
Problem in loading concepts and tables

### ISSUE THREAD

**Issue by priyendumori** [superscriptjs/superscript#335]
I am trying to follow silentrob's bot brit and he has a script bootstrapper.js which is supposed to load concepts and tables that bot needs as its knowledge but i am trying that and getting negative results i even tried to see mongodb content and found no data loaded. Can somebody help me with this?

And also knowledge section of wiki says something like below to load these data but i am not understanding anythiing in this code. Can someone explain it or give an example?

const superscript = require('superscript');
const options = {
  factSystem: {
    importData: [...],
    clean: true,
  },
  importFile: './data.json',
};

superscript.setup(options, (err, bot) => {
  botHandle(null, bot);
});

**Comment by benhjames** [comment]
All the options for setting up SuperScript can be found here, with descriptions of what each does below that: https://github.com/superscriptjs/superscript/blob/master/src/bot/index.js#L235

Hopefully all you need to do to load in concepts is pass your concept file names into the `factSystem.importData` array (which I think should actually be named `importFiles` - need to fix that). :)

Let us know if you run into issues with that!
