### ISSUE TITLE
gambit help for specific sentence. 

### ISSUE THREAD

**Issue by meghasoni** [superscriptjs/superscript#336]
need an help on this.
**not working :**
input to the system : KITAKAMBARA GUN SEIRO MACHI ,USA , 1 , JPN , 23 , 49
gambit : *~5 (,|:) *1 (,|:) * (,|:) *1 (,|:) ** (,|:) **

its not working, can you please help me on this, how to create gambit for the input, the words or numbers can be followed by space and , separating it.

if its without space and separated by commas, its working fine as below.
 
**working :**
input to the system : KITAKAMBARA GUN SEIRO MACHI ,USA,1 ,JPN,23 
gambit : *~5 (,|:) *1 (,|:) * (,|:) *1 (,|:) ** 

@benhjames  can you please help me on this.

**Comment by benhjames** [comment]
Hey, this isn't really something SuperScript is designed to do. SS works well with English sentences, but trying to match structured data isn't really a case that it's designed for, particularly with using punctuation as a delimiter.

You may want to try using a trigger filter function, which parses out the parts that you want with a regex. Something like:

```
+ {^matchesFormat()} *
```

where `matchesFormat` is your function that does something like `/.*/i.test(this.message.raw)`.
