### ISSUE TITLE
help needed for regex in input 

### ISSUE THREAD

**Issue by meghasoni** [superscriptjs/superscript#337]
+ {^**matchesFormat**()} *
- welcome home

**customFunction.js**

how to create **matchesFormat**  function to match with the regex
exports.matchesFormat = function(cb){
	console.log(/w*/.test(this.message.raw));
	cb();
}
 Can you please  provide sample for the matchesFormat function

@benhjames

**Comment by silentrob** [comment]
@meghasoni We don't provide this level of support. @benhjames was able to show the general gist of how that should work, and keep in mind that your original request falls out of scope for the type of problem superscript was designed to solve. If you want to move this forward, you might need to learn a little javascript.
