### ISSUE TITLE
Get an error when installing supescript with npm

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#340]
Can not install superscript due to upgrade of npm module tar. 
```
cd /tmp
npm install superscript
```

## Expected Behavior

SuperScript module is installed successfully.

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/3538629/25884305/e93ab98a-3583-11e7-8024-aa8c2a19f78d.png)
![image](https://cloud.githubusercontent.com/assets/3538629/25884309/f241fde0-3583-11e7-848c-a07be0828738.png)

## Possible Solution

In wndb-with-exceptions, it uses **latest** version of *tar*. 

1) fall back to v2.2.1 in package.json.

2) use the latest API of tar.

## Steps to Reproduce (for bugs)

```
npm install superscript
```
## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by Samurais** [comment]
# Relate with 

https://github.com/morungos/WNdb-with-exceptions/issues/1

**Comment by benhjames** [comment]
Should be fixed now!
