### ISSUE TITLE
Shorthand for alternate responses doesn't work

### ISSUE THREAD

**Issue by secretrobotron** [superscriptjs/superscript#342]
Using `(yes|no|maybe)` style of alternate doesn't seem to choose one. Instead, bot just responds with the whole string. The documentation suggests this is possible to do: https://github.com/superscriptjs/superscript/wiki/Replies

## Expected Behavior
This script

```
+ Do you like fish?
- Hmm.. (yes|no|maybe).
```

should result in `Hmm.. yes.`, `Hmm.. no.`, or `Hmm.. maybe.`.

## Current Behavior
It results in `Hmm.. (yes|no|maybe).`

## Possible Solution
🤷‍♀️
 
## Steps to Reproduce (for bugs)
1. Use the script above
2. Run a telnet bot (like the default one linked from https://www.npmjs.com/package/superscript)

## Context
I can't use this feature! But it's in the docs. Am I using it wrong?

## Your Environment

* Version used: `^1.0.0`
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): nodejs v7.9.0
* Server type and version: N/A
* Operating System and version: OSX
* Link to your project:

**Comment by benhjames** [comment]
Apologies, I think this should be double brackets instead of single brackets `((yes|no|maybe))`! Could you let us know if that works and we will fix the docs! 😃

**Comment by duffrind** [comment]
Hello,

I just tested that out and can confirm that using double brackets results in the intended response.

Just to reiterate:

(a|b|c) -> (a|b|c)
((a|b|c)) -> a OR b OR c

Thanks.

**Comment by benhjames** [comment]
Thanks - updated docs. :+1:
