### ISSUE TITLE
Generic wildcards cannot match ChineseChar as expect

### ISSUE THREAD

**Issue by lijiarui** [superscriptjs/superscript#345]
Thanks for your guys for writing this fantastic framework. I come from China and trying to build a ticket chatbot in Chinese and integrate superscript with [luis.ai](https://www.luis.ai/home/index)

I'm trying to use [generic-wildcards](https://github.com/superscriptjs/superscript/wiki/Triggers#generic-wildcards) to match some keywords but it failed because Chinese Char doesn't use a blank in a sentence as English do.

## Expected Behavior

I can use `* hello *` to match `Grace, hello, how are you` and it works well.
Trying to use `* 机票 *` to match `帮我订一张机票` but failed

## Current Behavior

Cannot use `* 机票 *` to match `帮我订一张机票`
I also tried using  `*机票*` to match `帮我订一张机票`, it failed too.
But using  `* 机票 *` can match `机票`

I thought the reason is  Chinese sentences doesn't use blank to split words.

## Possible Solution

Could you let generic-wildcards to match the word without blank or some other ways to remove the blank in the wildcards?

## Context

I'm trying to integrate superscript and luis.ai to build a chatbot to book tickets for a company message app, and I have tagged all my corpus and trained them successfully on luis.ai and api.ai.

At first, I used Microsoft's botframework to do this kind of thing but I found it is too complex, but superscript seems more light.

I don't care more about superscript functions support Chinese or not because I can use luis to do NLU part, but I need superscript to write the logic part of my chatbot.

I'll really appreciate if you can help to solve the generic-wildcards problems and give some suggestions, thanks!

**Comment by lijiarui** [comment]
More info

* `+ *(1|2|3|4|5)*` can match `我选择第1个`
* `+ *(1|2|3|4|5|一)*` can match `我选择第1个`
* `+ *(1|2|3|4|5|一)*` cannot match `我选择第一个`

**Comment by Nordes** [comment]
I would like to add that I have the same issue with Japanese :(. If you ever find a way to make it work, please share.

**Comment by lijiarui** [comment]
finally, I give up both superscript and rivescript, changing botframework instead, it can support Chinese well.

**Comment by silentrob** [comment]
Sorry SuperScript wasn't a better fit for your project.
