### ISSUE TITLE
Have a better documentation

### ISSUE THREAD

**Issue by Nordes** [superscriptjs/superscript#351]
Suggestion

This message is not about a bug, but more a request for better documentation. In order to find how the SuperScriptJS was working I had to search in the source code directly. I found it a bit annoying. 

Would it be possible to have a more complete documentation on a site like readthedocs.io (http://docs.readthedocs.io/en/latest/index.html)?

**Comment by silentrob** [comment]
Thanks for the suggestion. The docs are open source, and will get better over time. If you have a specific question about the docs or a feature, we can prop them up.

- Closing because this is too vague / subjective as a github issue.
