### ISSUE TITLE
let bot say first

### ISSUE THREAD

**Issue by zwj277567959** [superscriptjs/superscript#353]
how can I make my bot say something as soon as I jump into a new topic

**Comment by loganwilliams** [comment]
I'm also interested in how to do this. It's been referenced in a few previous issues, but the answers haven't. #24 #109

**Comment by mariusursache** [comment]
You can init the bot with something that sends a `__open__` first message to user (or do that in `pre` topic. Then, here's an example of self-started conversation:

```
// Learn user's first name
> topic:system:keep onboarding_01_id_name

  + __open__
  - What is your first name?

    + [my] [first] [name] [is] *1
    - <cap1>... That's a nice name. ^save(firstName,<cap1>)

< topic
```

**Comment by zwj277567959** [comment]
thank you
