### ISSUE TITLE
how to clear all vars of the user 

### ISSUE THREAD

**Issue by zwj277567959** [superscriptjs/superscript#354]
how to clear all vars of the user and how to show the list of vars

**Comment by benhjames** [comment]
I haven't tested this, but you could write a plugin like this for displaying all vars:

```js
const allVars = function allVars(cb) {
  const memory = this.user.memory;
  const userId = this.user.id;
  memory.db.get({ predicate: userId }, (err, res) => {
    console.log("Displaying all variables for user: ", userId);
    console.log(res);
  });
};
```

And then use it in a script like this: `^allVars()`

Deleting is slightly more complicated, you have to fetch all the variables (like above) and then delete them, but this link should help you along the way - look at the `save` plugin! https://github.com/superscriptjs/superscript/blob/master/src/plugins/user.js

**Comment by zwj277567959** [comment]
thank you very much  for your generous share ，it‘s helpful
