### ISSUE TITLE
Issue while conversation 

### ISSUE THREAD

**Issue by meghasoni** [superscriptjs/superscript#359]
Hi, 
 During the conversation with the bot, if the bot has to reply to previous question we use % in the Gambit. But once the bot replies to last reply and if the user ask some other questions it's replying the last reply again and again.
For example,

User: hi
Bot:hello
User: can you provide me details about mobile
Bot: enter mobile name
User:Samsung
Bot: good mobile to use
User:thanks
Bot:good mobile to use.

So if you see above after replying to previous question, the further questions are followed by same answer.

My ss file looks like below:

+ Hi
- hello

+ * Detail mobile *
- enter mobile name 

+ *1 
% enter mobile name
- ^getdetail() 

+ *
- I dint get you.

In the custom function just return 'good to use'
Help is appreciated.

**Comment by silentrob** [comment]
Please use triple ticks to show your code and avoid the auto-formatting. I think you might need to add a `{clear}` to the reply and force the conversation to reset.

**Comment by benhjames** [comment]
Closing as I believe issue was solved. If not, please re-open. 👍
