### ISSUE TITLE
Getting the default plugins into the telnet client

### ISSUE THREAD

**Issue by alexraj** [superscriptjs/superscript#371]
This is more of requesting information, rather than a issue.

I installed the mongodb and superscript, and the "telnet" client sample was working fine. I tried to go further and add more Gambits, that involves wordnet. I added the following to main.ss, but the ~sport is not getting resolved.

+ I ~like ~sport
- Yeah, I love ~sport too!

I believe the "plugins" directory under the sample client is empty, hence wordnet mappings are not found. How do I get all the built-in plugins?

Also, I see the hasToken function used in the sample, but this function is not listed in the "Functions and Plugins". Is there a comprehensive list of functions arranged in group of plugins?

**Comment by benhjames** [comment]
It should just work out the box! What does the parsed `json` file look like? If the trigger isn't expanded there then something has gone wrong... :)

Also, I'm not sure the `plugins` wiki is fully up-to-date, I think referring to `src/bot/plugins` is probably the best way for now.

**Comment by alexraj** [comment]
I used the command "bot-init testbot --clients telnet,slack" to create the nodejs project for my bot. The chat folder contains only main.ss, and the data.json contains only the gambits given in main.ss.

The plugins folder is empty. Will copying "bot" and "plugins" directory from source tree into my project get me all the gambits? I am not sure as there is no ".ss" files in the source tree.

**Comment by alexraj** [comment]
Sorry, it was my fault. My input was incorrect. I was expecting "I like ~sport" to match "I like baseball", actually it matches "I like sport", and reply contains actual sports name.
