### ISSUE TITLE
How to update to v1?

### ISSUE THREAD

**Issue by jenniferzhu** [superscriptjs/superscript#380]
This version thing drives me crazy...

**Comment by silentrob** [comment]
`npm install` will bring in 1.0 then read though the gotchas in the wiki https://github.com/superscriptjs/superscript/wiki/Upgrading-to-v1

**Comment by jenniferzhu** [comment]
But this version does not compile with the web application example:
https://github.com/silentrob/superscript-websocket-demo.

Do you know how to solve this issue? (The issue was mentioned several times
in the Issues on this example.)
