### ISSUE TITLE
Plugin & Functions Wiki Page Replies using +

### ISSUE THREAD

**Issue by macasas** [superscriptjs/superscript#402]
I'm a newborn here, looking at and trying to understand superscriptjs on day 1.  I'm going through the wiki to see how everything fits together.

Every page so far says + is a trigger, - is a reply

On Plugin & Functions page https://github.com/superscriptjs/superscript/wiki/Plugins-and-Functions it states in Multiple Functions and Nested Function, 2 examples of Replies, both starting with +

Does this + refer to something else involving functions, the Function reference page only shows them on - reply lines. Or is this just a typo left in to make sure we are all paying attention?

![screen shot 2018-05-07 at 16 47 54](https://user-images.githubusercontent.com/910082/39705510-4f4c4f3a-5217-11e8-8234-a68c86cc7197.png)

**Comment by silentrob** [comment]
Wow, you are  paying attention indeed. That was a typo, and now resolved.
Thanks for the comment.
